apiVersion: v1
kind: Pod
metadata:
  name: nginx-gvisor
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  runtimeClassName: gvisor
  tolerations:
    - key: k8s.scaleway.com/gvisor
      operator: Equal
      value: "enabled"
      effect: NoSchedule
  nodeSelector:
    k8s.scaleway.com/gvisor: enabled
